title: "Darsh Kale Test"
email: darshpkale@gmail.com
timezone: UTC
baseurl: ""
url: "https://dkale0.github.io"
permalink: "/:title/"
logo: 'assets/images/logo-1.png'
favicon: 'assets/images/favicon.ico'
author: darsh
paginate: 30
disqus: 
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: 
#UA-113961478-1

# Authors
authors:
  sal:
    name: Sal
    display_name: Sal
    avatar: 'assets/images/sal.png'
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://twitter.com/wowthemesnet
    description: "Author of Affiliates, a template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
  john:
    name: John
    display_name: John
    avatar: 'assets/images/john.png'
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Affiliates theme demo, a Jekyll template compatible with Github pages."
  darsh:
    name: Darsh
    display_name: Darsh
    avatar: 'assets/images/john.png'
    email: darshpkale@gmail.com
    web: 
    twitter: 
    description: "This is the author box. Write a short description of the author here. You are currently previewing Affiliates theme demo, a Jekyll template compatible with Github pages."
    

# Social
social:
  instagram: 
  facebook: 
  twitter: 
  github: https://github.com/Dkale0
  linkedin: https://www.linkedin.com/in/darsh-kale-8a00241b9/


# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives